// <auto-generated />
namespace GodSpeak.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApplicationUserProfileHasMessageDayOfWeekSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicationUserProfileHasMessageDayOfWeekSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161627196_ApplicationUserProfileHasMessageDayOfWeekSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
